# https://taskfile.dev

version: "3"

dotenv: [".env", "{{.ENV}}.env."]

tasks:
  default:
    cmds:
      - echo "Try --list-all to list all tasks"
    silent: true
  dev:
    cmds:
      - tailwindcss -i ./tailwind.css -o ./static/css/main.css
      - go generate
      - templ fmt ./shadcn
      - templ generate ./shadcn
      - go build -o ./shadcn-go
    silent: true
  prod:
    cmds:
      - tailwindcss -i ./tailwind.css -o ./static/css/main.css --minify
      - go generate
      - templ fmt ./shadcn
      - templ generate ./shadcn
      - go build -o ./shadcn-go
    silent: true
  run:
    deps: [dev]
    cmds:
      - ./shadcn-go
  run-prod:
    deps: [prod]
    cmds:
      - ./shadcn-go
  live:
    cmds:
      - air
    silent: true
